### ISSUE TITLE
Request: Autorun on startup

### ISSUE THREAD

**Issue by GRINX** [CentroFM/AudioLogger#34]
Can you add an autorun on startup in it, so it starts recording when the tool is started?

**Comment by devblok** [comment]
I had a plan to do something like this in v2.0, splitting the application into a Windows Service and the same simple GUI to work with it and a plan for Linux support (that's a bit tough to do, but maybe someday). The Windows Service side could be started on boot or however else you might want to start it. As the project itself has barely improved, since it already met our needs, so v2.0 never did land, even though work started a long time ago. Though I see you need this feature, I might as well reboot development on v2.0, though I can't speak ETA's yet :).

**Comment by devblok** [comment]
Refer to #31 for this feature's development
