### ISSUE TITLE
Volume meter does not reflect selected audio device

### ISSUE THREAD

**Issue by ValisVeckers** [CentroFM/AudioLogger#35]
After selecting a device in ComboBox, the volume meter does not reflect volume levels of selected device.

I see the code in `ApplicationForm.cs` `timer1_Tick` method is using default audio endpoint and there has been an attempt to use the selected device.

I've cloned the repo locally and I'll try to tackle this issue, but I'm using VS 2015 and it doesn't support InstallShield projects anymore. It will be a bit tricky to merge changes and submit a pull request but I'll try to do my best.

Also, please write code comments and variable names in English. Using Lithuanian is okay if the project is internal, but not if it is published on GitHub. I can read some basic Lithuanian and use Google translate when I can't understand, but other possible contributors might not even try.

BTW, there are some [new complaints/questions about AudioLogger on RadioDJ forums](http://www.radiodj.ro/community/index.php?topic=8992). It would be great if @ignazas joined in on the conversation.

**Comment by devblok** [comment]
Yeah, thanks for the heads up, I don't really follow the forum (guess I need to change that, because it gets some attention there). It's mostly me doing the developing for the project, mostly what I do is by request from @ignazas, since he's more aware of usage patterns and so on. I'm also trying to do small increments/improvements as I go along, rest assured, those comments in Lithuanian are on their way out whenever I will touch that code.

I'm also glad that some people find it useful, I'll try to help everyone get it running and fix bugs. You and anyone else can always reach me here.
